# Generated by Django 6.0.2 on 2026-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnthusiastInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('interest', models.CharField(choices=[('volunteer', 'Volunteer'), ('donate', 'Donate'), ('advocate', 'Advocate'), ('visit', 'Visit')], max_length=50)),
                ('background', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandownerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(choices=[('deployment', 'Ranger Deployment'), ('training', 'Staff Training'), ('management', 'Ranger Management'), ('consultation', 'Consultation')], max_length=50)),
                ('property_size', models.IntegerField(blank=True, null=True)),
                ('property_location', models.CharField(blank=True, max_length=200)),
                ('concerns_poaching', models.BooleanField(default=False)),
                ('concerns_human_wildlife', models.BooleanField(default=False)),
                ('concerns_livestock', models.BooleanField(default=False)),
                ('concerns_trespassing', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('media', 'Media / Press'), ('partnership', 'Partnership / Collaboration'), ('research', 'Research / Academic'), ('employment', 'Employment Opportunities'), ('supplier', 'Supplier / Vendor'), ('general', 'General Information'), ('other', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('urgency', models.CharField(choices=[('normal', 'Normal - Response within 3-5 days'), ('urgent', 'Urgent - Require prompt attention'), ('routine', 'Routine - No specific timeframe')], default='normal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('education', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(choices=[('basic', 'Basic Ranger Course'), ('specialist', 'Specialist Courses'), ('advanced', 'Advanced Ranger'), ('unsure', 'Not Sure')], max_length=50)),
                ('intake', models.CharField(blank=True, max_length=50)),
                ('experience', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
