# Generated by Django 4.2 on 2026-02-17 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_enthusiastinquiry_landownerinquiry_otherinquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='certificates',
            field=models.FileField(blank=True, help_text='Upload any relevant certificates (PDF, JPG, PNG)', null=True, upload_to='applications/certificates/'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='cv_resume',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF, DOC, DOCX)', null=True, upload_to='applications/cv/'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='dietary_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='id_document',
            field=models.FileField(blank=True, help_text='Upload your ID or Passport (PDF, JPG, PNG)', null=True, upload_to='applications/id_documents/'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any medical conditions we should be aware of'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='motivation_text',
            field=models.TextField(blank=True, help_text='Why you want to take this course'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='previous_experience',
            field=models.TextField(blank=True, help_text='Relevant experience in conservation, military, security, etc.'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Passport-sized photo (JPG, PNG)', null=True, upload_to='applications/photos/'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='additional_docs',
            field=models.FileField(blank=True, help_text='Any other supporting documents', null=True, upload_to='applications/additional/'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='main.applicantprofile'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.course'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='motivation_letter',
            field=models.FileField(blank=True, help_text='Upload your motivation letter (PDF, DOC, DOCX)', null=True, upload_to='applications/motivation/'),
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cv', 'CV/Resume'), ('id', 'ID Document'), ('certificate', 'Certificate'), ('photo', 'Profile Photo'), ('other', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
